# ARQUIVO DE DESINSTALAÇÃO DO BANCO DE DADOS.
# EXCLUINDO AS DUAS TABELAS DE BASE DE DADOS DE CONFIGURAÇÃO DO COMPONENTE.

# EXCLUINDO A BASE DE DADOS QUE CONTÉM AS ANIMAÇÕES.
# (É PRECISO EXCLUÍ-LA PRIMEIRO, POIS ELA APRESENTA UMA FOREIGN KEY).
DROP TABLE IF EXISTS `#__bannerperson_config_animation`;

# EXCLUIR A TABELA DE CONFIGURAÇÃO DO BANNER EM SI.
DROP TABLE IF EXISTS `#__bannerperson_config_banner`; 