# ARQUIVO DE DESINSTALAÇÃO DO BANCO DE DADOS.
# EXCLUINDO AS TABELA DE BASE DE DADOS DE CONFIGURAÇÃO DO COMPONENTE.

# EXCLUIR A TABELA DE CONFIGURAÇÃO DO BANNER EM SI.
DROP TABLE IF EXISTS `#__bannerperson_config_banner`;